use_frameworks!

platform :ios, '9.0'

target 'ReactNativeJuseRTC_Example' do
  pod 'ReactNativeJuseRTC', :path => '../'

  target 'ReactNativeJuseRTC_Tests' do
    inherit! :search_paths

    
  end
end
